### ISSUE TITLE
Uvoz

### ISSUE THREAD

**Issue by katarinabrilej** [evababnik/APPR-2019-20#3]
Pri uvozu tabel mora biti pot do datotek podana npr. kot
`
"podatki/delez_delovnih_migrantov_glede_na_delovno_akt_preb.csv"
`,
torej brez `APPR ANALIZA TRANSPORTA/` spredaj. 

Ko preimenuješ stolpce, lahko to narediš z enim ukazom, ni potrebno vsakega stolpca posebej preimenovati:
```
colnames(delez_delovnih_migrantov) <- c("statisticna_regija",2009:2019)
```

Tabelo pa je potrebno še urediti v obliko tidy data:
```
uvozi.migracije <- function(){
  delez_delovnih_migrantov <- read_delim("podatki/delez_delovnih_migrantov_glede_na_delovno_akt_preb.csv", 
                                                                   ";", escape_double = FALSE, trim_ws = TRUE, 
                                                                   skip = 1, col_names = TRUE, 
                                         locale=locale(encoding = 'Windows-1250'))
  colnames(delez_delovnih_migrantov) <- c("statisticna_regija",2009:2019)
  delez_delovnih_migrantov$`2019` <- NULL
  delez_delovnih_migrantov <- delez_delovnih_migrantov %>% pivot_longer(-statisticna_regija, names_to = "leto",values_to = "delez")
  return(delez_delovnih_migrantov)
}

delez_delovnih_migrantov <- uvozi.migracije()
```

Datoteke `stevilo_umrlih_v_cest_nesrecah_na_10000_preb.csv`, `povprecna_starost_avtomobilov.csv` in  `osebni_avtomobili_na_1000_preb.csv  ` se uvozijo na enak način, zato je bolje napisati samo eno funkcijo za uvoz, ki kot parameter sprejme ime datoteke. Prav tako jih je potrebno še urediti v tidy data obliko. 

```
uvozi <- function(ime_datoteke){
  ime <- paste0("podatki/", ime_datoteke, ".csv")
  tabela <- read_delim(ime, ";", escape_double = FALSE, trim_ws = TRUE, 
                       skip = 1,  col_names = TRUE, locale=locale(encoding = 'Windows-1250')) 
  tabela <- tabela[,2:12]
  colnames(tabela)[1] <- "statisticna_regija"
  tabela <- tabela %>% pivot_longer(-statisticna_regija, names_to = "leto",values_to = "vrednost")
  return(tabela)
}
  
starost_avtomobilov <- uvozi("povprecna_starost_avtomobilov")
colnames(starost_avtomobilov)[3] <- "starost_avtomobila"
stevilo_umrlih <- uvozi("stevilo_umrlih_v_cest_nesrecah_na_10000_preb")
colnames(stevilo_umrlih)[3] <- "stevilo_umrlih"
st_avtomobilov <- uvozi("osebni_avtomobili_na_1000_preb")
colnames(st_avtomobilov)[3] <- "st_avtomobilov"
```

**Comment by jaanos** [comment]
@evababnik, poskrbi, da imaš v RStudiu odprt projekt - če desno zgoraj piše *Project: (None)*, klikni tja, izberi *Open Project...*, nato pa poišči datoteko `APPR-2019-20.Rproj` v mapi svojega repozitorija (tako bo deloval tudi git znotraj RStudia). Tako bo delovni imenik nastavljen na vrhnjo mapo projekta in bo delovalo tudi branje datotek tako, kot je zgoraj napisala @katarinabrilej.

**Comment by jaanos** [comment]
Še to: glede na to, da imaš v razpredelnicah `starost_avtomobilov`, `stevilo_umrlih` in `st_avtomobilov` enaki dimenziji (regija in leto) ter da ti podatki niso med seboj neposredno primerljivi, bi jih lahko združila v eno razpredelnico z dvema dimenzijama in tremi meritvami, npr.
```R
stevilo_starost <- starost_avtomobilov %>% full_join(st_avtomobilov) %>% full_join(stevilo_umrlih)
```

Da se ti pri pretvorbi v *tidy data* leta pretvorijo v števila, lahko pri obeh zgornjih uporabah funkcije `pivot_longer` dodaš še parameter `names_transform=list(leto=parse_number)`.

**Comment by evababnik** [comment]
Super, najlepša hvala za popravke in pomoč pri uvozu, sem popravila.
Lep pozdrav, EVA
